import { PrismaClient } from '@prisma/client'
import { hash } from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting seed...')

  // Get or create a test user
  let user = await prisma.user.findFirst()

  if (!user) {
    console.log('No user found. Creating a test user...')
    const hashedPassword = await hash('password', 10)
    user = await prisma.user.create({
      data: {
        email: 'test@example.com',
        name: 'Test User',
        password: hashedPassword,
      },
    })
    console.log('✅ Created test user:', user.email)
  } else {
    console.log('✅ Using existing user:', user.email)
  }

  // Check if courses already exist for this user
  const existingCourses = await prisma.codingCourse.findMany({
    where: { userId: user.id },
  })

  if (existingCourses.length > 0) {
    console.log(`⚠️  User already has ${existingCourses.length} courses. Skipping seed.`)
    console.log('💡 To reseed, delete existing courses first or modify the seed script.')
    return
  }

  // Transformation start date and target date (180 days later)
  const transformationStartDate = new Date('2025-11-10')
  const targetDate = new Date(transformationStartDate)
  targetDate.setDate(targetDate.getDate() + 180)

  // All courses from main branch
  const coursesData = [
    {
      name: 'Modern React with Redux by Stephen Grider',
      modules: [
        { name: "Let's Dive In!", completed: true },
        { name: 'Creating Content with JSX', completed: false },
        { name: 'Building with Reusable Components', completed: false },
        { name: 'State: How to Change Your App', completed: false },
        { name: 'Using an API with React', completed: false },
        { name: 'How to Handle Forms', completed: false },
        { name: 'Data Persistence with API Requests', completed: false },
        { name: 'Communication Using the Context System', completed: false },
        { name: 'Deeper Dive into Hooks!', completed: false },
        { name: 'Custom Navigation with Routing Systems', completed: false },
        { name: 'Mastering the State Design Process', completed: false },
        { name: 'Practicing Props and State Design', completed: false },
        { name: 'Making Navigation Reusable', completed: false },
        { name: 'Creating Portals with ReactDOM', completed: false },
        { name: 'Make a Feature-Full Data Table!', completed: false },
        { name: 'Getting Clever with Data Sorting', completed: false },
        { name: 'Custom Hooks in Depth', completed: false },
        { name: 'Into the World of Reducers', completed: false },
        { name: 'Dive into Redux Toolkit', completed: false },
        { name: 'Managing Multiple Slices with Redux Toolkit', completed: false },
        { name: "Interfacing with API's using Async Thunks", completed: false },
        { name: 'Modern Async with Redux Toolkit Query', completed: false },
        { name: 'Diving Into TypeScript', completed: false },
        { name: 'Build a Google Maps Clone with Typescript', completed: false },
        { name: 'Navigation and Data Fetching with React Router', completed: false },
      ],
    },
    {
      name: 'React Query / TanStack Query: React Server State Management',
      modules: [
        { name: 'Creating Queries and Loading / Error states', completed: false },
        { name: 'Pagination, Pre-fetching and Mutations', completed: false },
        { name: 'Infinite Queries for Loading Data "Just in Time"', completed: false },
        { name: 'React Query in Larger App: Setup, Centralization, Custom Hooks', completed: false },
        { name: 'Query Features I: Pre-fetching and Pagination', completed: false },
        { name: 'Query Features II: Transforming and Re-Fetching data', completed: false },
        { name: 'React Query and Authentiacation', completed: false },
        { name: 'Mutations: Using React Query to Update Data on the Server', completed: false },
        { name: 'Testing React Query', completed: false },
      ],
    },
    {
      name: "Typescript: The Complete Developer's Guide",
      modules: [
        { name: 'Getting Started with Typescript', completed: false },
        { name: 'What is Type System?', completed: false },
        { name: 'Type Annotations in Action', completed: false },
        { name: 'Annotations With Functions and Objects', completed: false },
        { name: 'Mastering Typed Arrays', completed: false },
        { name: 'Tuples in Typescript', completed: false },
        { name: 'The All-Important Interface', completed: false },
        { name: 'Building Functionality with Classes', completed: false },
        { name: 'Design Patterns with Typescript', completed: false },
        { name: 'More on Design Patterns', completed: false },
        { name: 'Reusable Code', completed: false },
        { name: 'Advanced Generics', completed: false },
        { name: "Let's Build a Web Framework", completed: false },
        { name: 'Express + Typescript Integration', completed: false },
        { name: 'Decorators', completed: false },
        { name: 'Advanced Express and TS Integration', completed: false },
        { name: 'React and Redux Class Components with Typescript', completed: false },
        { name: 'React Functional Components with Typescript', completed: false },
        { name: 'Redux with Functional Components and Typescript', completed: false },
        { name: 'Extras', completed: false },
      ],
    },
    {
      name: 'CSS - The Complete Guide 2025 (incl. Flexbox, Grid & SASS)',
      modules: [
        { name: 'Getting Started', completed: false },
        { name: 'Diving Into the Basics of CSS', completed: false },
        { name: 'Diving Deeper into CSS', completed: false },
        { name: 'More on Selectors & CSS Features', completed: false },
        { name: 'Practicing the Basics', completed: false },
        { name: 'Positioning Elements with CSS', completed: false },
        { name: 'Understanding Background Images & Images', completed: false },
        { name: 'Sizes & Units', completed: false },
        { name: 'Working with JavaScript & CSS', completed: false },
        { name: 'Making our Website Responsive', completed: false },
        { name: 'Adding & Styling Forms', completed: false },
        { name: 'Working with Texts and Fonts', completed: false },
        { name: 'Adding Flexbox to our Project', completed: false },
        { name: 'Using the CSS Grid', completed: false },
        { name: 'Transforming Elements with CSS Transforms', completed: false },
        { name: 'Transitions & Animations in CSS', completed: false },
        { name: 'Writing Future-Proof CS Code', completed: false },
        { name: 'Introducing SASS', completed: false },
      ],
    },
    {
      name: 'Tailwind CSS From Scratch | Learn By Building Projects',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Tailwind Fundamentals - Part 1', completed: false },
        { name: 'Tailwind Fundamentals - Part 2', completed: false },
        { name: 'A Better Development Environment', completed: false },
        { name: 'Tailwind CSS Mini-Projects', completed: false },
        { name: 'Project 1 — Clipboard Website', completed: false },
        { name: 'Project 2 — Loopstudios Website', completed: false },
        { name: 'Project 3 — Shortly Website', completed: false },
        { name: 'Project 4 — Testimonial Grid Project', completed: false },
        { name: 'Project 5 — Fylo Website With Color Picker', completed: false },
        { name: 'Project 6 — Bookmark Manager Website', completed: false },
      ],
    },
    {
      name: 'Complete React Native Bootcamp (with Hooks)',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'React Native Fundamentals', completed: false },
        { name: 'The 2 Paths', completed: false },
        { name: 'Building with React Native: FocusTime App', completed: false },
        { name: 'Mobile Development Professional: Local Setup', completed: false },
        { name: 'Master Project: MealsToGo Project Setup', completed: false },
        { name: 'Master Project: MealsToGo Core Part 1', completed: false },
        { name: 'Master Project: MealsToGo Core Part 2', completed: false },
        { name: 'Extra: Mobile Camera Module', completed: false },
        { name: 'Extra: Google Maps Integration', completed: false },
        { name: 'Extra: Mobile Payments with stripe', completed: false },
        { name: 'Extra: Releasing To The App Stores', completed: false },
        { name: 'Extra: App Polish + Customizing MealsToGo', completed: false },
        { name: 'Keeping Youp App Up To Date', completed: false },
      ],
    },
    {
      name: 'App Academy Open JavaScript Track',
      modules: [
        { name: 'Web Development Fundamentals', completed: false },
        { name: 'JavaScript Fundamentals', completed: false },
        { name: 'Intermediate JavaScript', completed: false },
        { name: 'TDD and OOP', completed: false },
        { name: 'Data Structures and Algorithms', completed: false },
        { name: 'HTML and CSS', completed: false },
        { name: 'Servers, APIs and Promises', completed: false },
        { name: 'Frontend JavaScript', completed: false },
        { name: 'Express & SQL', completed: false },
        { name: 'Express & Sequelize', completed: false },
        { name: 'Web Security and Authentication', completed: false },
        { name: 'React', completed: false },
        { name: 'Redux and Authentication', completed: false },
      ],
    },
    {
      name: 'App Academy Open Ruby on Rails Track',
      modules: [
        { name: 'Ruby', completed: false },
        { name: 'SQL', completed: false },
        { name: 'Rails', completed: false },
        { name: 'Full-Stack Project', completed: false },
      ],
    },
    {
      name: 'React Testing Library and Jest: The Complete Guide',
      modules: [
        { name: "Dive In - Let's Get Started!", completed: false },
        { name: 'A Whirlwind Overview of Testing', completed: false },
        { name: 'Understanding Elements Roles', completed: false },
        { name: 'Finding Elements with Query Functions', completed: false },
        { name: 'Query Function Suffixes', completed: false },
        { name: 'Matchers in Jest', completed: false },
        { name: 'Big Project Overview', completed: false },
        { name: 'The Mysterious "Act" Function!', completed: false },
        { name: 'Handling Data Fetching in Tests', completed: false },
        { name: 'Tests Around Authentication', completed: false },
      ],
    },
    {
      name: 'Advanced React and Redux by Stephen Grider',
      modules: [
        { name: "Welcome! Let's Get Started!", completed: false },
        { name: 'Testing', completed: false },
        { name: 'Higher Order Components', completed: false },
        { name: 'Middlewares with Redux', completed: false },
        { name: 'Server Setup - Authentication', completed: false },
        { name: 'Client Side Auth', completed: false },
      ],
    },
    {
      name: 'Advanced React For Enterprise: React for Senior Engineers',
      modules: [
        { name: 'Introduction to Design systems', completed: false },
        { name: 'CSS Architecture', completed: false },
        { name: 'Monorepositories', completed: false },
        { name: 'Implementation of React', completed: false },
        { name: 'Accessibility for the select component', completed: false },
        { name: 'Unit testing atomic components', completed: false },
        { name: 'Storybook with react', completed: false },
        { name: 'Publish to `npm`', completed: false },
        { name: 'Github actions / CI / CD', completed: false },
      ],
    },
    {
      name: 'Master the Coding Interview: Data Structures + Algorithms',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Getting More Interviews', completed: false },
        { name: 'Big O', completed: false },
        { name: 'How to Solve Coding Problems', completed: false },
        { name: 'Data Structures: Introduction', completed: false },
        { name: 'Data Structures: Arrays', completed: false },
        { name: 'Data Structures: Hash Tables', completed: false },
        { name: 'Data Structures: Linked Lists', completed: false },
        { name: 'Data Structures: Stacks + Queues', completed: false },
        { name: 'Data Structures: Trees', completed: false },
        { name: 'Data Structures: Graphs', completed: false },
        { name: 'Algorithms: Recursion', completed: false },
        { name: 'Algorithms: Sorting', completed: false },
        { name: 'Algorithms: Searching + BFS + DFS', completed: false },
        { name: 'Algorithms: Dynamic Programming', completed: false },
        { name: 'Non Technical Interviews', completed: false },
        { name: 'Offer + Negotiations', completed: false },
      ],
    },
    {
      name: 'JavaScript Pro: Mastering Advanced Concepts and Techniques',
      modules: [
        { name: 'Introduction', completed: true },
        { name: 'Object Oriented JavaScript', completed: true },
        { name: 'OOP: Newer features in JavaScript', completed: false },
        { name: 'The Mysterious keyword "This"', completed: false },
        { name: 'OOP Under the Hood: Prototypes, New & More!', completed: false },
        { name: 'Asynchronous Code', completed: false },
        { name: 'Latest JavaScript Features', completed: false },
        { name: 'The Tricky Parts of JavaScript', completed: false },
        { name: 'The Tricky Parts: Scope & Closures', completed: false },
        { name: 'Timers: Debouncing, Throttling, & RequestAnimationFrame', completed: false },
        { name: 'Functional Programming', completed: false },
        { name: 'Fetch API', completed: false },
        { name: 'Web Storage APIs', completed: false },
        { name: 'Browser APIs: Geolocation, Intersection Observers, and More!', completed: false },
        { name: 'Performance API & Web Audio', completed: false },
        { name: 'Canvas API', completed: false },
        { name: 'Web Sockets API', completed: false },
        { name: 'Notifications API', completed: false },
        { name: 'SOLID OOP Principles', completed: false },
        { name: 'Design Patterns & Proxy Objects', completed: false },
      ],
    },
    {
      name: 'JavaScript Hard Parts',
      modules: [
        { name: 'JS — The Hard Parts', completed: false },
        { name: 'JS — The Hard Parts of Object Oriented JavaScript', completed: false },
        { name: 'JS — The New Hard Parts', completed: false },
      ],
    },
    {
      name: 'Namaste JavaScript by Akshay Saini',
      modules: [
        { name: 'Episode 1', completed: false },
        { name: 'Episode 2', completed: false },
        { name: 'Episode 3', completed: false },
        { name: 'Episode 4', completed: false },
        { name: 'Episode 5', completed: false },
        { name: 'Episode 6', completed: false },
        { name: 'Episode 7', completed: false },
        { name: 'Episode 8', completed: false },
        { name: 'Episode 9', completed: false },
        { name: 'Episode 10', completed: false },
        { name: 'Episode 11', completed: false },
        { name: 'Episode 12', completed: false },
        { name: 'Episode 13', completed: false },
        { name: 'Episode 14', completed: false },
        { name: 'Episode 15', completed: false },
        { name: 'Episode 16', completed: false },
        { name: 'Episode 17', completed: false },
        { name: 'Episode 18', completed: false },
        { name: 'Episode 19', completed: false },
        { name: 'Episode 20', completed: false },
      ],
    },
    {
      name: 'Javascript Interview Questions by Roadside Coder',
      modules: [
        { name: 'Video 1', completed: false },
        { name: 'Video 2', completed: false },
        { name: 'Video 3', completed: false },
        { name: 'Video 4', completed: false },
        { name: 'Video 5', completed: false },
        { name: 'Video 6', completed: false },
        { name: 'Video 7', completed: false },
        { name: 'Video 8', completed: false },
        { name: 'Video 9', completed: false },
        { name: 'Video 10', completed: false },
        { name: 'Video 11', completed: false },
        { name: 'Video 12', completed: false },
      ],
    },
    {
      name: 'Typescript Interview Questions',
      modules: [
        { name: 'Video 1', completed: false },
        { name: 'Video 2', completed: false },
        { name: 'Video 3', completed: false },
      ],
    },
    {
      name: 'Next.js 15 & React - The Complete Guide',
      modules: [
        { name: 'Getting Started', completed: false },
        { name: 'Optional: React Refresher', completed: false },
        { name: 'NextJS Essentials (App Router)', completed: false },
        { name: 'Routing & Page Rendering - Deep Dive', completed: false },
        { name: 'Data Fetching - Deep Dive', completed: false },
        { name: 'Mutating Data - Deep Dive', completed: false },
        { name: 'Understanding & Configuring Caching', completed: false },
        { name: 'NextJS App Optimizations', completed: false },
        { name: 'User Authentication', completed: false },
        { name: 'Roundup & Next Steps', completed: false },
        { name: 'Pages & File-based Routing', completed: false },
        { name: 'Project Time: Working with File based Routing', completed: false },
        { name: 'Page Pre-Rendering & Data Fetching', completed: false },
        { name: 'Project Time: Page Pre-rendering & Data Fetching', completed: false },
        { name: 'Optimizing NextJS Apps', completed: false },
        { name: 'Adding Backend Code with API Routes (Fullstack React)', completed: false },
        { name: 'Project Time: API Routes', completed: false },
        { name: 'Working with App-wide State (React Context)', completed: false },
        { name: 'Complete App Example: Build a Full Blog A to Z', completed: false },
        { name: 'Deploying NextJS Apps', completed: false },
        { name: 'Adding Authentication', completed: false },
        { name: 'Optional: NextJS Summary', completed: false },
        { name: 'Course Roundup', completed: false },
      ],
    },
    {
      name: "Microfrontends with React: A Complete Developer's Guide",
      modules: [
        { name: 'The Basics of Microfrontends', completed: false },
        { name: 'The Basics of Module Federation', completed: false },
        { name: 'Sharing Dependencies Between Apps', completed: false },
        { name: 'Linking Multiple Apps Together', completed: false },
        { name: 'Generic Ties Between Projects', completed: false },
        { name: 'Implementing a CI/CD Pipeline', completed: false },
        { name: 'Deployment to Amazon Web Services', completed: false },
        { name: 'Microfrontend-Specific AWS Config', completed: false },
        { name: 'Handling CSS in Microfrontends', completed: false },
        { name: 'Implementing Multi-Tier Navigation', completed: false },
        { name: 'Performance Considerations', completed: false },
        { name: 'Authentication in Microfrontends', completed: false },
        { name: 'Using Other frontend Frameworks', completed: false },
      ],
    },
    {
      name: 'Progressive Web Apps (PWA) - The Complete Guide',
      modules: [
        { name: 'Getting Started', completed: false },
        { name: 'Understanding the App Manifest', completed: false },
        { name: 'The Service Workers', completed: false },
        { name: 'Promise and fetch', completed: false },
        { name: 'Service Workers - Caching', completed: false },
        { name: 'Service Workers - Advanced Caching', completed: false },
        { name: 'IndexedDB and Dynamic Data', completed: false },
        { name: 'Creating a Responsive User Interface (UI)', completed: false },
        { name: 'Background Sync', completed: false },
        { name: 'Web Push Notifications', completed: false },
        { name: 'Native Device Features', completed: false },
        { name: 'Service Worker Management with Workbox', completed: false },
        { name: 'SPAs and PWAs', completed: false },
        { name: 'Course Roundup', completed: false },
      ],
    },
    {
      name: 'React Interview Questions by RoadSide Coder',
      modules: [
        { name: 'Video 1', completed: false },
        { name: 'Video 2', completed: false },
        { name: 'Video 3', completed: false },
        { name: 'Video 4', completed: false },
        { name: 'Video 5', completed: false },
        { name: 'Video 6', completed: false },
        { name: 'Video 7', completed: false },
        { name: 'Video 8', completed: false },
        { name: 'Video 9', completed: false },
        { name: 'Video 10', completed: false },
        { name: 'Video 11', completed: false },
        { name: 'Video 12', completed: false },
        { name: 'Video 13', completed: false },
        { name: 'Video 14', completed: false },
        { name: 'Video 15', completed: false },
        { name: 'Video 16', completed: false },
        { name: 'Video 17', completed: false },
        { name: 'Video 18', completed: false },
        { name: 'Video 19', completed: false },
        { name: 'Video 20', completed: false },
        { name: 'Video 21', completed: false },
      ],
    },
    {
      name: 'System Design Questions',
      modules: [{ name: 'Playlist', completed: false }],
    },
    {
      name: 'Complete NodeJS Developer (GraphQL, MongoDB, +more)',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Node.js Fundamentals: Foundations and Environment Setup', completed: false },
        { name: 'Node.js Fundamentals: Internals', completed: false },
        { name: 'Node.js Fundamentals: Module System', completed: false },
        { name: 'Node.js Fundamentals: Package Management', completed: false },
        { name: 'Node.js File I/O - Planets Project', completed: false },
        { name: 'Web Servers with Node.js', completed: false },
        { name: 'First Express.js API', completed: false },
        { name: 'NASA Project', completed: false },
        { name: 'Testing APIs', completed: false },
        { name: 'Improving Node Performance', completed: false },
        { name: 'Databases', completed: false },
        { name: 'Working With REST APIs - SpaceX Project', completed: false },
        { name: 'Node Security + Authentication', completed: false },
        { name: 'Continuous Integration and Delivery', completed: false },
        { name: 'Node Production and the Cloud (Docker + AWS)', completed: false },
        { name: 'GraphQL', completed: false },
        { name: 'Sockets with Node.js', completed: false },
      ],
    },
    {
      name: "SQL and PostgreSQL: The Complete Developer's Guide",
      modules: [
        { name: 'Simple - But Powerful - SQL Statements', completed: false },
        { name: 'Filtering Records', completed: false },
        { name: 'Working with Tables', completed: false },
        { name: 'Relating Records with Joins', completed: false },
        { name: 'Aggregation of Records', completed: false },
        { name: 'Working with Large Datasets', completed: false },
        { name: 'Sorting Records', completed: false },
        { name: 'Unions and Intersections with Sets', completed: false },
        { name: 'Assembling Queries with SubQueries', completed: false },
        { name: 'Selecting Distinct Records', completed: false },
        { name: 'Utility Operators, Keywords and Functions', completed: false },
        { name: 'Local PostgreSQL Installation', completed: false },
        { name: 'PostgreSQL Complex Datatypes', completed: false },
        { name: 'Database-Side Validation and Constraints', completed: false },
        { name: 'Database Structure Design Patterns', completed: false },
        { name: "How to Build a 'Like' System", completed: false },
        { name: "How to Build a 'Mention' System", completed: false },
        { name: "How to Build a 'Hashtag' System", completed: false },
        { name: "How to Design a 'Follower' System", completed: false },
        { name: 'Implementing Database Design Patterns', completed: false },
        { name: 'Approaching and Writing Complex Queries', completed: false },
        { name: 'Understanding the Internals of PostgreSQL', completed: false },
        { name: 'A Look at Indexes for Performance', completed: false },
        { name: 'Basic Query Tuning', completed: false },
        { name: 'Advanced Query Tuning', completed: false },
        { name: 'Simple Common Table Expressions', completed: false },
        { name: 'Recursive Common Table Expressions', completed: false },
        { name: 'Simplifying Queries with Views', completed: false },
        { name: 'Optimizing Queries with Materialized Views', completed: false },
        { name: 'Handling Concurrency and Reversibility with Transactions', completed: false },
        { name: 'Managing Database Design with Schema Migrations', completed: false },
        { name: 'Schema vs Data Migrations', completed: false },
        { name: 'Accessing PostgreSQL From APIs', completed: false },
        { name: 'Data Access Pattern - Repositories', completed: false },
        { name: 'Security Around PostgreSQL', completed: false },
        { name: 'Fast Parallel Testing', completed: false },
      ],
    },
    {
      name: "MongoDB — The Complete Developer's Guide 2025",
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Understanding the Basics & CRUD Operations', completed: false },
        { name: 'Schemas & Relations: How to Structure Documents', completed: false },
        { name: 'Exploring the Shell & the Server', completed: false },
        { name: 'Using the MongoDB Compass to Explore Data Visually', completed: false },
        { name: 'Diving into create operations', completed: false },
        { name: 'Read Operations - A closer look', completed: false },
        { name: 'Update Operations', completed: false },
        { name: 'Understanding Delete Operations', completed: false },
        { name: 'Working with Indexes', completed: false },
        { name: 'Working with Geospatial Data', completed: false },
        { name: 'Understanding the Aggregation Framework', completed: false },
        { name: 'Working with Numeric Data', completed: false },
        { name: 'MongoDB & Security', completed: false },
        { name: 'Performance, Fault Tolerancy & Deployment', completed: false },
        { name: 'Transactions', completed: false },
        { name: 'From Shell to Driver', completed: false },
        { name: 'Introducing Stitch', completed: false },
        { name: 'Roundup', completed: false },
      ],
    },
    {
      name: 'Node JS: Advanced Concepts',
      modules: [
        { name: 'The Internals of Node', completed: false },
        { name: 'Enhancing Node Performance', completed: false },
        { name: 'Project Setup', completed: false },
        { name: 'Data Caching with Redis', completed: false },
        { name: 'Automated Headless Browser Testing', completed: false },
        { name: 'Wiring up Continuous Integration', completed: false },
        { name: 'Scalable Image/File Upload', completed: false },
        { name: 'Extras', completed: false },
      ],
    },
    {
      name: "Redis: The Complete Developer's Guide",
      modules: [
        { name: 'Get Started Here!', completed: false },
        { name: 'Commands for Adding and Querying Data', completed: false },
        { name: 'E-Commerce App Setup', completed: false },
        { name: 'Local Redis Setup', completed: false },
        { name: 'Hash Data Structures', completed: false },
        { name: "Redis Has Gotcha's!", completed: false },
        { name: 'Powerful Design Patterns', completed: false },
        { name: 'Pipelining Commands', completed: false },
        { name: 'Enforcing Uniqueness with Sets', completed: false },
        { name: 'A little Set Implementation', completed: false },
        { name: 'Onganizing Data with Sorted Sets', completed: false },
        { name: 'Practice Time with Sorted Sets!', completed: false },
        { name: 'From Relational Data to Redis', completed: false },
        { name: 'HyperLogLog Structures', completed: false },
        { name: 'Storing Collections with Lists', completed: false },
        { name: 'More Practice with the E-Commerce App', completed: false },
        { name: 'Extending Redis with Scripting', completed: false },
        { name: 'Understanding and Solving concurrency issues', completed: false },
        { name: 'Querying Data with RedisSearch', completed: false },
        { name: 'Search in Action', completed: false },
        { name: 'Service Communication with Streams', completed: false },
      ],
    },
    {
      name: 'Webpack 5: The Complete Guide For Beginners',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Initial Setup and Integrating Webpack', completed: false },
        { name: 'Asset Modules', completed: false },
        { name: 'Loaders', completed: false },
        { name: 'Plugins', completed: false },
        { name: 'Production vs Development Builds', completed: false },
        { name: 'Multiple Page Applications and Code Splitting', completed: false },
        { name: 'Github Repository', completed: false },
        { name: 'Webpack integration with Node and Express', completed: false },
        { name: 'Module Federation', completed: false },
        { name: 'Integration with jQuery', completed: false },
        { name: 'Using EsLint', completed: false },
        { name: 'Summary', completed: false },
      ],
    },
    {
      name: 'Docker and Kubernetes: The Complete Guide',
      modules: [
        { name: 'Dive Into Docker!', completed: false },
        { name: 'Manipulating Containers with the Docker Client', completed: false },
        { name: 'Building Custom Images Through Docker Server', completed: false },
        { name: 'Making Real Projects with Docker', completed: false },
        { name: 'Docker Compose with Multiple Local Containers', completed: false },
        { name: 'Creating a Production-Grade Workflow', completed: false },
        { name: 'Continuous Integration and Deployment with AWS', completed: false },
        { name: 'Building a Multi-Container Application', completed: false },
        { name: 'Dockerizing Multiple Services', completed: false },
        { name: 'A Continuous Integration Workflow for Multiple Images', completed: false },
        { name: 'Multi-Container Deployments to AWS', completed: false },
        { name: 'Onwards to Kubernetes!', completed: false },
        { name: 'Maintaining Sets of Containers with Deployments', completed: false },
        { name: 'A Multi-Container App with Kubernetes', completed: false },
        { name: 'Handling Traffic with Ingress Controllers', completed: false },
        { name: 'Kubernetes Production Deployment', completed: false },
        { name: 'HTTPS Setup with Kubernetes', completed: false },
        { name: 'Local Development with Skaffold', completed: false },
      ],
    },
    {
      name: 'Microservices with NodeJS and React',
      modules: [
        { name: 'Fundamental Ideas Around Microservices', completed: false },
        { name: 'A Mini-Microservices App', completed: false },
        { name: 'Running Services with Docker', completed: false },
        { name: 'Orchestrating Collections of Services with Kubernetes', completed: false },
        { name: 'Architecture of Multi-Service App', completed: false },
        { name: 'Leveraging a Cloud Environment for Development', completed: false },
        { name: 'Response Normalization Strategies', completed: false },
        { name: 'Database Management and Modeling', completed: false },
        { name: 'Authentication Strategies and Options', completed: false },
        { name: 'Testing Isolated Microservices', completed: false },
        { name: 'Integrating a Server-Side-Rendered React App', completed: false },
        { name: 'Code Sharing and Reuse Between Services', completed: false },
        { name: 'Create-Read-Update-Destroy Server Setup', completed: false },
        { name: 'NATS Streaming Server - An Event Bus Implementation', completed: false },
        { name: 'Connecting to NATS in a NodeJS World', completed: false },
        { name: 'Managing a NATS Client', completed: false },
        { name: 'Cross-Service Data Replication in Action', completed: false },
        { name: 'Understanding Event Flow', completed: false },
        { name: 'Listening for Events and Handling Concurrency Issues', completed: false },
        { name: 'Worker Services', completed: false },
        { name: 'Handling Payments', completed: false },
        { name: 'Back to the Client', completed: false },
        { name: 'CI/CD', completed: false },
      ],
    },
    {
      name: 'DevOps Beginners to Advanced with Projects',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Prerequisites Info & Setup', completed: false },
        { name: 'VM Setup', completed: false },
        { name: 'Linux', completed: false },
        { name: 'Vagrant & Linux Servers', completed: false },
        { name: 'Variables, JSON & YAML', completed: false },
        { name: 'VProfile Project Setup Manual & Automated', completed: false },
        { name: 'Networking', completed: false },
        { name: 'Introducing Containers', completed: false },
        { name: 'Bash Scripting', completed: false },
        { name: 'AWS Part - 1', completed: false },
        { name: 'AWS Cloud for project set up | Lift & Shift', completed: false },
        { name: 'Re-Architecting Web App on AWS Cloud [PASS & SASS]', completed: false },
        { name: 'GIT', completed: false },
        { name: 'Maven', completed: false },
        { name: 'Continuous Integration with Jenkins', completed: false },
        { name: 'Python', completed: false },
        { name: 'Learn Terraform', completed: false },
        { name: 'Ansible', completed: false },
        { name: 'AWS Part-2', completed: false },
        { name: 'AWS CI/CD Project', completed: false },
        { name: 'Docker', completed: false },
        { name: 'Containerization', completed: false },
        { name: 'Kubernetes', completed: false },
        { name: 'App Deployment on Kubernetes Cluster', completed: false },
        { name: 'GitOps Project', completed: false },
        { name: 'Conclusion', completed: false },
      ],
    },
    {
      name: 'DevOps Projects | Real Time DevOps & GitOps Projects',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Pre-requisites Info & Setup', completed: false },
        { name: 'VM Setup MacOS M1 Chip', completed: false },
        { name: 'Multi Tier Web Application Setup, Locally', completed: false },
        { name: 'Automated Setup of Multi Tier App, Locally', completed: false },
        { name: 'AWS Cloud for Web App Setup [ Lift & Shift ]', completed: false },
        { name: 'Re-Architecting Web App on AWS Cloud [ Cloud Native ]', completed: false },
        { name: 'Containerization of Java project using Docker', completed: false },
        { name: 'Jenkins Pipeline As A Code(Groovy) Project', completed: false },
        { name: 'Continuous Integration Using Jenkins, Nexus, Sonarqube & Slack', completed: false },
        { name: 'Continuous Integration on AWS Cloud', completed: false },
        { name: 'Continuous Delivery of Java Web Application', completed: false },
        { name: 'Continuous Delivery on AWS Cloud [ Java Application ]', completed: false },
        { name: 'Github Actions for CI/CD', completed: false },
        { name: 'Kuberenetes Setup for productions', completed: false },
        { name: 'Java App Deployment on Kubernetes Cluster', completed: false },
        { name: 'Terraform Tutorials', completed: false },
        { name: 'Terraform for Cloud State Management', completed: false },
        { name: 'GitOps Project', completed: false },
        { name: 'Continuous Delivery And Configuration Management [Jenkins plus Ansible]', completed: false },
        { name: 'Hybrid Continuous Delivery', completed: false },
        { name: 'CICD for Containers', completed: false },
        { name: 'Ansible for AWS VPC [Phase One]', completed: false },
        { name: 'Ansible for Complete Stack Setup [Phase Two]', completed: false },
        { name: 'Ansible for Complete Stack Setup [Phase Three]', completed: false },
      ],
    },
    {
      name: 'Ultimate AWS Certified Solutions Architect Associate 2025',
      modules: [
        { name: 'Introduction - AWS Certified Solutions Architect Associate', completed: false },
        { name: 'Code & Slides Download', completed: false },
        { name: 'Getting started with AWS', completed: false },
        { name: 'IAM & AWS CLI', completed: false },
        { name: 'EC2 Fundamentals', completed: false },
        { name: 'EC2 - Solutions Architect Associate Level', completed: false },
        { name: 'EC2 Instance Storage', completed: false },
        { name: 'High Availability and Scalability: ELB & ASG', completed: false },
        { name: 'AWS Fundamentals: RDS + Aurora + ElastiCache', completed: false },
        { name: 'Route 53', completed: false },
        { name: 'Classic Solutions Architecture Discussions', completed: false },
        { name: 'Amazon S3 Introduction', completed: false },
        { name: 'Advanced Amazon S3', completed: false },
        { name: 'Amazon S3 Security', completed: false },
        { name: 'CloudFront & AWS Global Accelerator', completed: false },
        { name: 'AWS Storage Extras', completed: false },
        { name: 'Decoupling applications: SQS, SNS, Kinesis, Active MQ', completed: false },
        { name: 'Containers on AWS: ECS, Fargate, ECR & EKS', completed: false },
        { name: 'Serverless Overview from a Solution Architect Perspective', completed: false },
        { name: 'Serverless Solution Architecture Discussions', completed: false },
        { name: 'Databases in AWS', completed: false },
        { name: 'Data & Analytics', completed: false },
        { name: 'Machine Learning', completed: false },
        { name: 'AWS Monitoring & Audit: CloudWatch, CloudTrail & Config', completed: false },
        { name: 'Identity and Access Management (IAM) - Advanced', completed: false },
        { name: 'AWS Security & Encryption: KMS, SSM Parameter Store, Shield, WAF', completed: false },
        { name: 'Networking - VPC', completed: false },
        { name: 'Disaster Recovery & Migrations', completed: false },
        { name: 'More Solution Architectures', completed: false },
        { name: 'Other Services', completed: false },
        { name: 'WhitePapers and Architectures - AWS Certified Solutions Architect Associate', completed: false },
        { name: 'Preparing for the Exam + Practice Exam - AWS Certified Solutions Architect Associate Certification', completed: false },
        { name: 'Congratulations - AWS Certified Solutions Architect Associate', completed: false },
      ],
    },
  ]

  // Create courses with modules
  for (const courseData of coursesData) {
    const { modules, ...courseInfo } = courseData
    const course = await prisma.codingCourse.create({
      data: {
        name: courseInfo.name,
        description: courseInfo.description,
        userId: user.id,
        startDate: transformationStartDate,
        targetDate: targetDate,
        modules: {
          create: modules.map((module, index) => ({
            name: module.name,
            order: index + 1,
            completed: module.completed,
            completedAt: module.completed ? new Date() : null,
          })),
        },
      },
      include: {
        modules: true,
      },
    })
    console.log(`✅ Created course: ${course.name} with ${course.modules.length} modules`)
  }

  console.log('🎉 Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Error during seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
