import { PrismaClient } from '@prisma/client'
import { hash } from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting seed...')

  // Get or create a test user
  let user = await prisma.user.findFirst()

  if (!user) {
    console.log('No user found. Creating a test user...')
    const hashedPassword = await hash('password', 10)
    user = await prisma.user.create({
      data: {
        email: 'test@example.com',
        name: 'Test User',
        password: hashedPassword,
      },
    })
    console.log('✅ Created test user:', user.email)
  } else {
    console.log('✅ Using existing user:', user.email)
  }

  // Check if courses already exist for this user
  const existingCodingCourses = await prisma.codingCourse.findMany({
    where: { userId: user.id },
  })

  if (existingCodingCourses.length > 0) {
    console.log(`⚠️  User already has ${existingCodingCourses.length} coding courses. Skipping coding seed.`)
    console.log('💡 To reseed, delete existing courses first or modify the seed script.')
  }

  // Check if trading courses already exist for this user
  const existingTradingCourses = await prisma.tradingCourse.findMany({
    where: { userId: user.id },
  })

  if (existingTradingCourses.length > 0) {
    console.log(`⚠️  User already has ${existingTradingCourses.length} trading courses. Skipping trading seed.`)
    console.log('💡 To reseed, delete existing courses first or modify the seed script.')
  }

  if (existingCodingCourses.length > 0 && existingTradingCourses.length > 0) {
    return
  }

  // Transformation start date and target date (180 days later)
  const transformationStartDate = new Date('2025-11-10')
  const targetDate = new Date(transformationStartDate)
  targetDate.setDate(targetDate.getDate() + 180)

  // All courses from main branch
  const coursesData = [
    {
      name: 'Modern React with Redux by Stephen Grider',
      modules: [
        { name: "Let's Dive In!", completed: true },
        { name: 'Creating Content with JSX', completed: false },
        { name: 'Building with Reusable Components', completed: false },
        { name: 'State: How to Change Your App', completed: false },
        { name: 'Using an API with React', completed: false },
        { name: 'How to Handle Forms', completed: false },
        { name: 'Data Persistence with API Requests', completed: false },
        { name: 'Communication Using the Context System', completed: false },
        { name: 'Deeper Dive into Hooks!', completed: false },
        { name: 'Custom Navigation with Routing Systems', completed: false },
        { name: 'Mastering the State Design Process', completed: false },
        { name: 'Practicing Props and State Design', completed: false },
        { name: 'Making Navigation Reusable', completed: false },
        { name: 'Creating Portals with ReactDOM', completed: false },
        { name: 'Make a Feature-Full Data Table!', completed: false },
        { name: 'Getting Clever with Data Sorting', completed: false },
        { name: 'Custom Hooks in Depth', completed: false },
        { name: 'Into the World of Reducers', completed: false },
        { name: 'Dive into Redux Toolkit', completed: false },
        { name: 'Managing Multiple Slices with Redux Toolkit', completed: false },
        { name: "Interfacing with API's using Async Thunks", completed: false },
        { name: 'Modern Async with Redux Toolkit Query', completed: false },
        { name: 'Diving Into TypeScript', completed: false },
        { name: 'Build a Google Maps Clone with Typescript', completed: false },
        { name: 'Navigation and Data Fetching with React Router', completed: false },
      ],
    },
    {
      name: 'React Query / TanStack Query: React Server State Management',
      modules: [
        { name: 'Creating Queries and Loading / Error states', completed: false },
        { name: 'Pagination, Pre-fetching and Mutations', completed: false },
        { name: 'Infinite Queries for Loading Data "Just in Time"', completed: false },
        { name: 'React Query in Larger App: Setup, Centralization, Custom Hooks', completed: false },
        { name: 'Query Features I: Pre-fetching and Pagination', completed: false },
        { name: 'Query Features II: Transforming and Re-Fetching data', completed: false },
        { name: 'React Query and Authentiacation', completed: false },
        { name: 'Mutations: Using React Query to Update Data on the Server', completed: false },
        { name: 'Testing React Query', completed: false },
      ],
    },
    {
      name: "Typescript: The Complete Developer's Guide",
      modules: [
        { name: 'Getting Started with Typescript', completed: false },
        { name: 'What is Type System?', completed: false },
        { name: 'Type Annotations in Action', completed: false },
        { name: 'Annotations With Functions and Objects', completed: false },
        { name: 'Mastering Typed Arrays', completed: false },
        { name: 'Tuples in Typescript', completed: false },
        { name: 'The All-Important Interface', completed: false },
        { name: 'Building Functionality with Classes', completed: false },
        { name: 'Design Patterns with Typescript', completed: false },
        { name: 'More on Design Patterns', completed: false },
        { name: 'Reusable Code', completed: false },
        { name: 'Advanced Generics', completed: false },
        { name: "Let's Build a Web Framework", completed: false },
        { name: 'Express + Typescript Integration', completed: false },
        { name: 'Decorators', completed: false },
        { name: 'Advanced Express and TS Integration', completed: false },
        { name: 'React and Redux Class Components with Typescript', completed: false },
        { name: 'React Functional Components with Typescript', completed: false },
        { name: 'Redux with Functional Components and Typescript', completed: false },
        { name: 'Extras', completed: false },
      ],
    },
    {
      name: 'CSS - The Complete Guide 2025 (incl. Flexbox, Grid & SASS)',
      modules: [
        { name: 'Getting Started', completed: false },
        { name: 'Diving Into the Basics of CSS', completed: false },
        { name: 'Diving Deeper into CSS', completed: false },
        { name: 'More on Selectors & CSS Features', completed: false },
        { name: 'Practicing the Basics', completed: false },
        { name: 'Positioning Elements with CSS', completed: false },
        { name: 'Understanding Background Images & Images', completed: false },
        { name: 'Sizes & Units', completed: false },
        { name: 'Working with JavaScript & CSS', completed: false },
        { name: 'Making our Website Responsive', completed: false },
        { name: 'Adding & Styling Forms', completed: false },
        { name: 'Working with Texts and Fonts', completed: false },
        { name: 'Adding Flexbox to our Project', completed: false },
        { name: 'Using the CSS Grid', completed: false },
        { name: 'Transforming Elements with CSS Transforms', completed: false },
        { name: 'Transitions & Animations in CSS', completed: false },
        { name: 'Writing Future-Proof CS Code', completed: false },
        { name: 'Introducing SASS', completed: false },
      ],
    },
    {
      name: 'Tailwind CSS From Scratch | Learn By Building Projects',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Tailwind Fundamentals - Part 1', completed: false },
        { name: 'Tailwind Fundamentals - Part 2', completed: false },
        { name: 'A Better Development Environment', completed: false },
        { name: 'Tailwind CSS Mini-Projects', completed: false },
        { name: 'Project 1 — Clipboard Website', completed: false },
        { name: 'Project 2 — Loopstudios Website', completed: false },
        { name: 'Project 3 — Shortly Website', completed: false },
        { name: 'Project 4 — Testimonial Grid Project', completed: false },
        { name: 'Project 5 — Fylo Website With Color Picker', completed: false },
        { name: 'Project 6 — Bookmark Manager Website', completed: false },
      ],
    },
    {
      name: 'Complete React Native Bootcamp (with Hooks)',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'React Native Fundamentals', completed: false },
        { name: 'The 2 Paths', completed: false },
        { name: 'Building with React Native: FocusTime App', completed: false },
        { name: 'Mobile Development Professional: Local Setup', completed: false },
        { name: 'Master Project: MealsToGo Project Setup', completed: false },
        { name: 'Master Project: MealsToGo Core Part 1', completed: false },
        { name: 'Master Project: MealsToGo Core Part 2', completed: false },
        { name: 'Extra: Mobile Camera Module', completed: false },
        { name: 'Extra: Google Maps Integration', completed: false },
        { name: 'Extra: Mobile Payments with stripe', completed: false },
        { name: 'Extra: Releasing To The App Stores', completed: false },
        { name: 'Extra: App Polish + Customizing MealsToGo', completed: false },
        { name: 'Keeping Youp App Up To Date', completed: false },
      ],
    },
    {
      name: 'App Academy Open JavaScript Track',
      modules: [
        { name: 'Web Development Fundamentals', completed: false },
        { name: 'JavaScript Fundamentals', completed: false },
        { name: 'Intermediate JavaScript', completed: false },
        { name: 'TDD and OOP', completed: false },
        { name: 'Data Structures and Algorithms', completed: false },
        { name: 'HTML and CSS', completed: false },
        { name: 'Servers, APIs and Promises', completed: false },
        { name: 'Frontend JavaScript', completed: false },
        { name: 'Express & SQL', completed: false },
        { name: 'Express & Sequelize', completed: false },
        { name: 'Web Security and Authentication', completed: false },
        { name: 'React', completed: false },
        { name: 'Redux and Authentication', completed: false },
      ],
    },
    {
      name: 'App Academy Open Ruby on Rails Track',
      modules: [
        { name: 'Ruby', completed: false },
        { name: 'SQL', completed: false },
        { name: 'Rails', completed: false },
        { name: 'Full-Stack Project', completed: false },
      ],
    },
    {
      name: 'React Testing Library and Jest: The Complete Guide',
      modules: [
        { name: "Dive In - Let's Get Started!", completed: false },
        { name: 'A Whirlwind Overview of Testing', completed: false },
        { name: 'Understanding Elements Roles', completed: false },
        { name: 'Finding Elements with Query Functions', completed: false },
        { name: 'Query Function Suffixes', completed: false },
        { name: 'Matchers in Jest', completed: false },
        { name: 'Big Project Overview', completed: false },
        { name: 'The Mysterious "Act" Function!', completed: false },
        { name: 'Handling Data Fetching in Tests', completed: false },
        { name: 'Tests Around Authentication', completed: false },
      ],
    },
    {
      name: 'Advanced React and Redux by Stephen Grider',
      modules: [
        { name: "Welcome! Let's Get Started!", completed: false },
        { name: 'Testing', completed: false },
        { name: 'Higher Order Components', completed: false },
        { name: 'Middlewares with Redux', completed: false },
        { name: 'Server Setup - Authentication', completed: false },
        { name: 'Client Side Auth', completed: false },
      ],
    },
    {
      name: 'Advanced React For Enterprise: React for Senior Engineers',
      modules: [
        { name: 'Introduction to Design systems', completed: false },
        { name: 'CSS Architecture', completed: false },
        { name: 'Monorepositories', completed: false },
        { name: 'Implementation of React', completed: false },
        { name: 'Accessibility for the select component', completed: false },
        { name: 'Unit testing atomic components', completed: false },
        { name: 'Storybook with react', completed: false },
        { name: 'Publish to `npm`', completed: false },
        { name: 'Github actions / CI / CD', completed: false },
      ],
    },
    {
      name: 'Master the Coding Interview: Data Structures + Algorithms',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Getting More Interviews', completed: false },
        { name: 'Big O', completed: false },
        { name: 'How to Solve Coding Problems', completed: false },
        { name: 'Data Structures: Introduction', completed: false },
        { name: 'Data Structures: Arrays', completed: false },
        { name: 'Data Structures: Hash Tables', completed: false },
        { name: 'Data Structures: Linked Lists', completed: false },
        { name: 'Data Structures: Stacks + Queues', completed: false },
        { name: 'Data Structures: Trees', completed: false },
        { name: 'Data Structures: Graphs', completed: false },
        { name: 'Algorithms: Recursion', completed: false },
        { name: 'Algorithms: Sorting', completed: false },
        { name: 'Algorithms: Searching + BFS + DFS', completed: false },
        { name: 'Algorithms: Dynamic Programming', completed: false },
        { name: 'Non Technical Interviews', completed: false },
        { name: 'Offer + Negotiations', completed: false },
      ],
    },
    {
      name: 'JavaScript Pro: Mastering Advanced Concepts and Techniques',
      modules: [
        { name: 'Introduction', completed: true },
        { name: 'Object Oriented JavaScript', completed: true },
        { name: 'OOP: Newer features in JavaScript', completed: false },
        { name: 'The Mysterious keyword "This"', completed: false },
        { name: 'OOP Under the Hood: Prototypes, New & More!', completed: false },
        { name: 'Asynchronous Code', completed: false },
        { name: 'Latest JavaScript Features', completed: false },
        { name: 'The Tricky Parts of JavaScript', completed: false },
        { name: 'The Tricky Parts: Scope & Closures', completed: false },
        { name: 'Timers: Debouncing, Throttling, & RequestAnimationFrame', completed: false },
        { name: 'Functional Programming', completed: false },
        { name: 'Fetch API', completed: false },
        { name: 'Web Storage APIs', completed: false },
        { name: 'Browser APIs: Geolocation, Intersection Observers, and More!', completed: false },
        { name: 'Performance API & Web Audio', completed: false },
        { name: 'Canvas API', completed: false },
        { name: 'Web Sockets API', completed: false },
        { name: 'Notifications API', completed: false },
        { name: 'SOLID OOP Principles', completed: false },
        { name: 'Design Patterns & Proxy Objects', completed: false },
      ],
    },
    {
      name: 'JavaScript Hard Parts',
      modules: [
        { name: 'JS — The Hard Parts', completed: false },
        { name: 'JS — The Hard Parts of Object Oriented JavaScript', completed: false },
        { name: 'JS — The New Hard Parts', completed: false },
      ],
    },
    {
      name: 'Namaste JavaScript by Akshay Saini',
      modules: [
        { name: 'Episode 1', completed: false },
        { name: 'Episode 2', completed: false },
        { name: 'Episode 3', completed: false },
        { name: 'Episode 4', completed: false },
        { name: 'Episode 5', completed: false },
        { name: 'Episode 6', completed: false },
        { name: 'Episode 7', completed: false },
        { name: 'Episode 8', completed: false },
        { name: 'Episode 9', completed: false },
        { name: 'Episode 10', completed: false },
        { name: 'Episode 11', completed: false },
        { name: 'Episode 12', completed: false },
        { name: 'Episode 13', completed: false },
        { name: 'Episode 14', completed: false },
        { name: 'Episode 15', completed: false },
        { name: 'Episode 16', completed: false },
        { name: 'Episode 17', completed: false },
        { name: 'Episode 18', completed: false },
        { name: 'Episode 19', completed: false },
        { name: 'Episode 20', completed: false },
      ],
    },
    {
      name: 'Javascript Interview Questions by Roadside Coder',
      modules: [
        { name: 'Video 1', completed: false },
        { name: 'Video 2', completed: false },
        { name: 'Video 3', completed: false },
        { name: 'Video 4', completed: false },
        { name: 'Video 5', completed: false },
        { name: 'Video 6', completed: false },
        { name: 'Video 7', completed: false },
        { name: 'Video 8', completed: false },
        { name: 'Video 9', completed: false },
        { name: 'Video 10', completed: false },
        { name: 'Video 11', completed: false },
        { name: 'Video 12', completed: false },
      ],
    },
    {
      name: 'Typescript Interview Questions',
      modules: [
        { name: 'Video 1', completed: false },
        { name: 'Video 2', completed: false },
        { name: 'Video 3', completed: false },
      ],
    },
    {
      name: 'Next.js 15 & React - The Complete Guide',
      modules: [
        { name: 'Getting Started', completed: false },
        { name: 'Optional: React Refresher', completed: false },
        { name: 'NextJS Essentials (App Router)', completed: false },
        { name: 'Routing & Page Rendering - Deep Dive', completed: false },
        { name: 'Data Fetching - Deep Dive', completed: false },
        { name: 'Mutating Data - Deep Dive', completed: false },
        { name: 'Understanding & Configuring Caching', completed: false },
        { name: 'NextJS App Optimizations', completed: false },
        { name: 'User Authentication', completed: false },
        { name: 'Roundup & Next Steps', completed: false },
        { name: 'Pages & File-based Routing', completed: false },
        { name: 'Project Time: Working with File based Routing', completed: false },
        { name: 'Page Pre-Rendering & Data Fetching', completed: false },
        { name: 'Project Time: Page Pre-rendering & Data Fetching', completed: false },
        { name: 'Optimizing NextJS Apps', completed: false },
        { name: 'Adding Backend Code with API Routes (Fullstack React)', completed: false },
        { name: 'Project Time: API Routes', completed: false },
        { name: 'Working with App-wide State (React Context)', completed: false },
        { name: 'Complete App Example: Build a Full Blog A to Z', completed: false },
        { name: 'Deploying NextJS Apps', completed: false },
        { name: 'Adding Authentication', completed: false },
        { name: 'Optional: NextJS Summary', completed: false },
        { name: 'Course Roundup', completed: false },
      ],
    },
    {
      name: "Microfrontends with React: A Complete Developer's Guide",
      modules: [
        { name: 'The Basics of Microfrontends', completed: false },
        { name: 'The Basics of Module Federation', completed: false },
        { name: 'Sharing Dependencies Between Apps', completed: false },
        { name: 'Linking Multiple Apps Together', completed: false },
        { name: 'Generic Ties Between Projects', completed: false },
        { name: 'Implementing a CI/CD Pipeline', completed: false },
        { name: 'Deployment to Amazon Web Services', completed: false },
        { name: 'Microfrontend-Specific AWS Config', completed: false },
        { name: 'Handling CSS in Microfrontends', completed: false },
        { name: 'Implementing Multi-Tier Navigation', completed: false },
        { name: 'Performance Considerations', completed: false },
        { name: 'Authentication in Microfrontends', completed: false },
        { name: 'Using Other frontend Frameworks', completed: false },
      ],
    },
    {
      name: 'Progressive Web Apps (PWA) - The Complete Guide',
      modules: [
        { name: 'Getting Started', completed: false },
        { name: 'Understanding the App Manifest', completed: false },
        { name: 'The Service Workers', completed: false },
        { name: 'Promise and fetch', completed: false },
        { name: 'Service Workers - Caching', completed: false },
        { name: 'Service Workers - Advanced Caching', completed: false },
        { name: 'IndexedDB and Dynamic Data', completed: false },
        { name: 'Creating a Responsive User Interface (UI)', completed: false },
        { name: 'Background Sync', completed: false },
        { name: 'Web Push Notifications', completed: false },
        { name: 'Native Device Features', completed: false },
        { name: 'Service Worker Management with Workbox', completed: false },
        { name: 'SPAs and PWAs', completed: false },
        { name: 'Course Roundup', completed: false },
      ],
    },
    {
      name: 'React Interview Questions by RoadSide Coder',
      modules: [
        { name: 'Video 1', completed: false },
        { name: 'Video 2', completed: false },
        { name: 'Video 3', completed: false },
        { name: 'Video 4', completed: false },
        { name: 'Video 5', completed: false },
        { name: 'Video 6', completed: false },
        { name: 'Video 7', completed: false },
        { name: 'Video 8', completed: false },
        { name: 'Video 9', completed: false },
        { name: 'Video 10', completed: false },
        { name: 'Video 11', completed: false },
        { name: 'Video 12', completed: false },
        { name: 'Video 13', completed: false },
        { name: 'Video 14', completed: false },
        { name: 'Video 15', completed: false },
        { name: 'Video 16', completed: false },
        { name: 'Video 17', completed: false },
        { name: 'Video 18', completed: false },
        { name: 'Video 19', completed: false },
        { name: 'Video 20', completed: false },
        { name: 'Video 21', completed: false },
      ],
    },
    {
      name: 'System Design Questions',
      modules: [{ name: 'Playlist', completed: false }],
    },
    {
      name: 'Complete NodeJS Developer (GraphQL, MongoDB, +more)',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Node.js Fundamentals: Foundations and Environment Setup', completed: false },
        { name: 'Node.js Fundamentals: Internals', completed: false },
        { name: 'Node.js Fundamentals: Module System', completed: false },
        { name: 'Node.js Fundamentals: Package Management', completed: false },
        { name: 'Node.js File I/O - Planets Project', completed: false },
        { name: 'Web Servers with Node.js', completed: false },
        { name: 'First Express.js API', completed: false },
        { name: 'NASA Project', completed: false },
        { name: 'Testing APIs', completed: false },
        { name: 'Improving Node Performance', completed: false },
        { name: 'Databases', completed: false },
        { name: 'Working With REST APIs - SpaceX Project', completed: false },
        { name: 'Node Security + Authentication', completed: false },
        { name: 'Continuous Integration and Delivery', completed: false },
        { name: 'Node Production and the Cloud (Docker + AWS)', completed: false },
        { name: 'GraphQL', completed: false },
        { name: 'Sockets with Node.js', completed: false },
      ],
    },
    {
      name: "SQL and PostgreSQL: The Complete Developer's Guide",
      modules: [
        { name: 'Simple - But Powerful - SQL Statements', completed: false },
        { name: 'Filtering Records', completed: false },
        { name: 'Working with Tables', completed: false },
        { name: 'Relating Records with Joins', completed: false },
        { name: 'Aggregation of Records', completed: false },
        { name: 'Working with Large Datasets', completed: false },
        { name: 'Sorting Records', completed: false },
        { name: 'Unions and Intersections with Sets', completed: false },
        { name: 'Assembling Queries with SubQueries', completed: false },
        { name: 'Selecting Distinct Records', completed: false },
        { name: 'Utility Operators, Keywords and Functions', completed: false },
        { name: 'Local PostgreSQL Installation', completed: false },
        { name: 'PostgreSQL Complex Datatypes', completed: false },
        { name: 'Database-Side Validation and Constraints', completed: false },
        { name: 'Database Structure Design Patterns', completed: false },
        { name: "How to Build a 'Like' System", completed: false },
        { name: "How to Build a 'Mention' System", completed: false },
        { name: "How to Build a 'Hashtag' System", completed: false },
        { name: "How to Design a 'Follower' System", completed: false },
        { name: 'Implementing Database Design Patterns', completed: false },
        { name: 'Approaching and Writing Complex Queries', completed: false },
        { name: 'Understanding the Internals of PostgreSQL', completed: false },
        { name: 'A Look at Indexes for Performance', completed: false },
        { name: 'Basic Query Tuning', completed: false },
        { name: 'Advanced Query Tuning', completed: false },
        { name: 'Simple Common Table Expressions', completed: false },
        { name: 'Recursive Common Table Expressions', completed: false },
        { name: 'Simplifying Queries with Views', completed: false },
        { name: 'Optimizing Queries with Materialized Views', completed: false },
        { name: 'Handling Concurrency and Reversibility with Transactions', completed: false },
        { name: 'Managing Database Design with Schema Migrations', completed: false },
        { name: 'Schema vs Data Migrations', completed: false },
        { name: 'Accessing PostgreSQL From APIs', completed: false },
        { name: 'Data Access Pattern - Repositories', completed: false },
        { name: 'Security Around PostgreSQL', completed: false },
        { name: 'Fast Parallel Testing', completed: false },
      ],
    },
    {
      name: "MongoDB — The Complete Developer's Guide 2025",
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Understanding the Basics & CRUD Operations', completed: false },
        { name: 'Schemas & Relations: How to Structure Documents', completed: false },
        { name: 'Exploring the Shell & the Server', completed: false },
        { name: 'Using the MongoDB Compass to Explore Data Visually', completed: false },
        { name: 'Diving into create operations', completed: false },
        { name: 'Read Operations - A closer look', completed: false },
        { name: 'Update Operations', completed: false },
        { name: 'Understanding Delete Operations', completed: false },
        { name: 'Working with Indexes', completed: false },
        { name: 'Working with Geospatial Data', completed: false },
        { name: 'Understanding the Aggregation Framework', completed: false },
        { name: 'Working with Numeric Data', completed: false },
        { name: 'MongoDB & Security', completed: false },
        { name: 'Performance, Fault Tolerancy & Deployment', completed: false },
        { name: 'Transactions', completed: false },
        { name: 'From Shell to Driver', completed: false },
        { name: 'Introducing Stitch', completed: false },
        { name: 'Roundup', completed: false },
      ],
    },
    {
      name: 'Node JS: Advanced Concepts',
      modules: [
        { name: 'The Internals of Node', completed: false },
        { name: 'Enhancing Node Performance', completed: false },
        { name: 'Project Setup', completed: false },
        { name: 'Data Caching with Redis', completed: false },
        { name: 'Automated Headless Browser Testing', completed: false },
        { name: 'Wiring up Continuous Integration', completed: false },
        { name: 'Scalable Image/File Upload', completed: false },
        { name: 'Extras', completed: false },
      ],
    },
    {
      name: "Redis: The Complete Developer's Guide",
      modules: [
        { name: 'Get Started Here!', completed: false },
        { name: 'Commands for Adding and Querying Data', completed: false },
        { name: 'E-Commerce App Setup', completed: false },
        { name: 'Local Redis Setup', completed: false },
        { name: 'Hash Data Structures', completed: false },
        { name: "Redis Has Gotcha's!", completed: false },
        { name: 'Powerful Design Patterns', completed: false },
        { name: 'Pipelining Commands', completed: false },
        { name: 'Enforcing Uniqueness with Sets', completed: false },
        { name: 'A little Set Implementation', completed: false },
        { name: 'Onganizing Data with Sorted Sets', completed: false },
        { name: 'Practice Time with Sorted Sets!', completed: false },
        { name: 'From Relational Data to Redis', completed: false },
        { name: 'HyperLogLog Structures', completed: false },
        { name: 'Storing Collections with Lists', completed: false },
        { name: 'More Practice with the E-Commerce App', completed: false },
        { name: 'Extending Redis with Scripting', completed: false },
        { name: 'Understanding and Solving concurrency issues', completed: false },
        { name: 'Querying Data with RedisSearch', completed: false },
        { name: 'Search in Action', completed: false },
        { name: 'Service Communication with Streams', completed: false },
      ],
    },
    {
      name: 'Webpack 5: The Complete Guide For Beginners',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Initial Setup and Integrating Webpack', completed: false },
        { name: 'Asset Modules', completed: false },
        { name: 'Loaders', completed: false },
        { name: 'Plugins', completed: false },
        { name: 'Production vs Development Builds', completed: false },
        { name: 'Multiple Page Applications and Code Splitting', completed: false },
        { name: 'Github Repository', completed: false },
        { name: 'Webpack integration with Node and Express', completed: false },
        { name: 'Module Federation', completed: false },
        { name: 'Integration with jQuery', completed: false },
        { name: 'Using EsLint', completed: false },
        { name: 'Summary', completed: false },
      ],
    },
    {
      name: 'Docker and Kubernetes: The Complete Guide',
      modules: [
        { name: 'Dive Into Docker!', completed: false },
        { name: 'Manipulating Containers with the Docker Client', completed: false },
        { name: 'Building Custom Images Through Docker Server', completed: false },
        { name: 'Making Real Projects with Docker', completed: false },
        { name: 'Docker Compose with Multiple Local Containers', completed: false },
        { name: 'Creating a Production-Grade Workflow', completed: false },
        { name: 'Continuous Integration and Deployment with AWS', completed: false },
        { name: 'Building a Multi-Container Application', completed: false },
        { name: 'Dockerizing Multiple Services', completed: false },
        { name: 'A Continuous Integration Workflow for Multiple Images', completed: false },
        { name: 'Multi-Container Deployments to AWS', completed: false },
        { name: 'Onwards to Kubernetes!', completed: false },
        { name: 'Maintaining Sets of Containers with Deployments', completed: false },
        { name: 'A Multi-Container App with Kubernetes', completed: false },
        { name: 'Handling Traffic with Ingress Controllers', completed: false },
        { name: 'Kubernetes Production Deployment', completed: false },
        { name: 'HTTPS Setup with Kubernetes', completed: false },
        { name: 'Local Development with Skaffold', completed: false },
      ],
    },
    {
      name: 'Microservices with NodeJS and React',
      modules: [
        { name: 'Fundamental Ideas Around Microservices', completed: false },
        { name: 'A Mini-Microservices App', completed: false },
        { name: 'Running Services with Docker', completed: false },
        { name: 'Orchestrating Collections of Services with Kubernetes', completed: false },
        { name: 'Architecture of Multi-Service App', completed: false },
        { name: 'Leveraging a Cloud Environment for Development', completed: false },
        { name: 'Response Normalization Strategies', completed: false },
        { name: 'Database Management and Modeling', completed: false },
        { name: 'Authentication Strategies and Options', completed: false },
        { name: 'Testing Isolated Microservices', completed: false },
        { name: 'Integrating a Server-Side-Rendered React App', completed: false },
        { name: 'Code Sharing and Reuse Between Services', completed: false },
        { name: 'Create-Read-Update-Destroy Server Setup', completed: false },
        { name: 'NATS Streaming Server - An Event Bus Implementation', completed: false },
        { name: 'Connecting to NATS in a NodeJS World', completed: false },
        { name: 'Managing a NATS Client', completed: false },
        { name: 'Cross-Service Data Replication in Action', completed: false },
        { name: 'Understanding Event Flow', completed: false },
        { name: 'Listening for Events and Handling Concurrency Issues', completed: false },
        { name: 'Worker Services', completed: false },
        { name: 'Handling Payments', completed: false },
        { name: 'Back to the Client', completed: false },
        { name: 'CI/CD', completed: false },
      ],
    },
    {
      name: 'DevOps Beginners to Advanced with Projects',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Prerequisites Info & Setup', completed: false },
        { name: 'VM Setup', completed: false },
        { name: 'Linux', completed: false },
        { name: 'Vagrant & Linux Servers', completed: false },
        { name: 'Variables, JSON & YAML', completed: false },
        { name: 'VProfile Project Setup Manual & Automated', completed: false },
        { name: 'Networking', completed: false },
        { name: 'Introducing Containers', completed: false },
        { name: 'Bash Scripting', completed: false },
        { name: 'AWS Part - 1', completed: false },
        { name: 'AWS Cloud for project set up | Lift & Shift', completed: false },
        { name: 'Re-Architecting Web App on AWS Cloud [PASS & SASS]', completed: false },
        { name: 'GIT', completed: false },
        { name: 'Maven', completed: false },
        { name: 'Continuous Integration with Jenkins', completed: false },
        { name: 'Python', completed: false },
        { name: 'Learn Terraform', completed: false },
        { name: 'Ansible', completed: false },
        { name: 'AWS Part-2', completed: false },
        { name: 'AWS CI/CD Project', completed: false },
        { name: 'Docker', completed: false },
        { name: 'Containerization', completed: false },
        { name: 'Kubernetes', completed: false },
        { name: 'App Deployment on Kubernetes Cluster', completed: false },
        { name: 'GitOps Project', completed: false },
        { name: 'Conclusion', completed: false },
      ],
    },
    {
      name: 'DevOps Projects | Real Time DevOps & GitOps Projects',
      modules: [
        { name: 'Introduction', completed: false },
        { name: 'Pre-requisites Info & Setup', completed: false },
        { name: 'VM Setup MacOS M1 Chip', completed: false },
        { name: 'Multi Tier Web Application Setup, Locally', completed: false },
        { name: 'Automated Setup of Multi Tier App, Locally', completed: false },
        { name: 'AWS Cloud for Web App Setup [ Lift & Shift ]', completed: false },
        { name: 'Re-Architecting Web App on AWS Cloud [ Cloud Native ]', completed: false },
        { name: 'Containerization of Java project using Docker', completed: false },
        { name: 'Jenkins Pipeline As A Code(Groovy) Project', completed: false },
        { name: 'Continuous Integration Using Jenkins, Nexus, Sonarqube & Slack', completed: false },
        { name: 'Continuous Integration on AWS Cloud', completed: false },
        { name: 'Continuous Delivery of Java Web Application', completed: false },
        { name: 'Continuous Delivery on AWS Cloud [ Java Application ]', completed: false },
        { name: 'Github Actions for CI/CD', completed: false },
        { name: 'Kuberenetes Setup for productions', completed: false },
        { name: 'Java App Deployment on Kubernetes Cluster', completed: false },
        { name: 'Terraform Tutorials', completed: false },
        { name: 'Terraform for Cloud State Management', completed: false },
        { name: 'GitOps Project', completed: false },
        { name: 'Continuous Delivery And Configuration Management [Jenkins plus Ansible]', completed: false },
        { name: 'Hybrid Continuous Delivery', completed: false },
        { name: 'CICD for Containers', completed: false },
        { name: 'Ansible for AWS VPC [Phase One]', completed: false },
        { name: 'Ansible for Complete Stack Setup [Phase Two]', completed: false },
        { name: 'Ansible for Complete Stack Setup [Phase Three]', completed: false },
      ],
    },
    {
      name: 'Ultimate AWS Certified Solutions Architect Associate 2025',
      modules: [
        { name: 'Introduction - AWS Certified Solutions Architect Associate', completed: false },
        { name: 'Code & Slides Download', completed: false },
        { name: 'Getting started with AWS', completed: false },
        { name: 'IAM & AWS CLI', completed: false },
        { name: 'EC2 Fundamentals', completed: false },
        { name: 'EC2 - Solutions Architect Associate Level', completed: false },
        { name: 'EC2 Instance Storage', completed: false },
        { name: 'High Availability and Scalability: ELB & ASG', completed: false },
        { name: 'AWS Fundamentals: RDS + Aurora + ElastiCache', completed: false },
        { name: 'Route 53', completed: false },
        { name: 'Classic Solutions Architecture Discussions', completed: false },
        { name: 'Amazon S3 Introduction', completed: false },
        { name: 'Advanced Amazon S3', completed: false },
        { name: 'Amazon S3 Security', completed: false },
        { name: 'CloudFront & AWS Global Accelerator', completed: false },
        { name: 'AWS Storage Extras', completed: false },
        { name: 'Decoupling applications: SQS, SNS, Kinesis, Active MQ', completed: false },
        { name: 'Containers on AWS: ECS, Fargate, ECR & EKS', completed: false },
        { name: 'Serverless Overview from a Solution Architect Perspective', completed: false },
        { name: 'Serverless Solution Architecture Discussions', completed: false },
        { name: 'Databases in AWS', completed: false },
        { name: 'Data & Analytics', completed: false },
        { name: 'Machine Learning', completed: false },
        { name: 'AWS Monitoring & Audit: CloudWatch, CloudTrail & Config', completed: false },
        { name: 'Identity and Access Management (IAM) - Advanced', completed: false },
        { name: 'AWS Security & Encryption: KMS, SSM Parameter Store, Shield, WAF', completed: false },
        { name: 'Networking - VPC', completed: false },
        { name: 'Disaster Recovery & Migrations', completed: false },
        { name: 'More Solution Architectures', completed: false },
        { name: 'Other Services', completed: false },
        { name: 'WhitePapers and Architectures - AWS Certified Solutions Architect Associate', completed: false },
        { name: 'Preparing for the Exam + Practice Exam - AWS Certified Solutions Architect Associate Certification', completed: false },
        { name: 'Congratulations - AWS Certified Solutions Architect Associate', completed: false },
      ],
    },
  ]

  // Create coding courses with modules
  if (existingCodingCourses.length === 0) {
    for (const courseData of coursesData) {
      const { modules, ...courseInfo } = courseData
      const course = await prisma.codingCourse.create({
        data: {
          name: courseInfo.name,
          description: courseInfo.description,
          userId: user.id,
          startDate: transformationStartDate,
          targetDate: targetDate,
          modules: {
            create: modules.map((module, index) => ({
              name: module.name,
              order: index + 1,
              completed: module.completed,
              completedAt: module.completed ? new Date() : null,
            })),
          },
        },
        include: {
          modules: true,
        },
      })
      console.log(`✅ Created coding course: ${course.name} with ${course.modules.length} modules`)
    }
  }

  // Trading courses data
  const tradingCoursesData = [
    {
      name: "A Beginner's Guide to the Stock Market — Matthew R. Kratter",
      modules: [
        { name: "Chapter 1: The World's Greatest Opportunity Machine", completed: false },
        { name: 'Chapter 2: How to Get Started with Stocks', completed: false },
        { name: 'Chapter 3: Make Money with ETFs', completed: false },
        { name: 'Chapter 4: Passive Income with Dividend Stocks', completed: false },
        { name: 'Chapter 5: Investor Psychology', completed: false },
        { name: 'Chapter 6: Common Mistakes to Avoid', completed: false },
        { name: 'Chapter 7: Basic Trading Strategies', completed: false },
        { name: 'Chapter 8: Next Steps', completed: false },
      ],
    },
    {
      name: 'The Psychology of Money — Morgan Housel',
      modules: [
        { name: "Chapter 1: No One's Crazy", completed: false },
        { name: 'Chapter 2: Luck & Risk', completed: false },
        { name: 'Chapter 3: Never Enough', completed: false },
        { name: 'Chapter 4: Confounding Compounding', completed: false },
        { name: 'Chapter 5: Getting Wealthy vs Staying Wealthy', completed: false },
        { name: 'Chapter 6: Tails, You Win', completed: false },
        { name: 'Chapter 7: Freedom', completed: false },
        { name: 'Chapter 8: Man in the Car Paradox', completed: false },
        { name: "Chapter 9: Wealth is What You Don't See", completed: false },
        { name: 'Chapter 10: Save Money', completed: false },
        { name: 'Chapter 11: Reasonable > Rational', completed: false },
        { name: 'Chapter 12: Surprise!', completed: false },
        { name: 'Chapter 13: Room for Error', completed: false },
        { name: "Chapter 14: You'll Change", completed: false },
        { name: "Chapter 15: Nothing's Free", completed: false },
        { name: 'Chapter 16: You & Me', completed: false },
        { name: 'Chapter 17: Seduction of Pessimism', completed: false },
        { name: "Chapter 18: When You'll Believe Anything", completed: false },
        { name: 'Chapter 19: All Together Now', completed: false },
        { name: 'Chapter 20: Confessions', completed: false },
      ],
    },
    {
      name: 'Trading in the Zone — Mark Douglas',
      modules: [
        { name: 'Chapter 1: The Road to Success: Fundamental, Technical, or Mental Analysis?', completed: false },
        { name: 'Chapter 2: The Lure (And the Dangers) of Trading', completed: false },
        { name: 'Chapter 3: Taking Responsibility', completed: false },
        { name: 'Chapter 4: Consistency: A State of Mind', completed: false },
        { name: 'Chapter 5: The Dynamics of Perception', completed: false },
        { name: "Chapter 6: The Market's Perspective", completed: false },
        { name: "Chapter 7: The Trader's Edge: Thinking in Probabilities", completed: false },
        { name: 'Chapter 8: Working With Your Beliefs', completed: false },
        { name: 'Chapter 9: The Nature of Beliefs', completed: false },
        { name: 'Chapter 10: Impact of Beliefs on Trading', completed: false },
        { name: 'Chapter 11: Thinking Like a Trader', completed: false },
      ],
    },
    {
      name: 'Getting Started in Technical Analysis — Jack Schwager',
      modules: [
        { name: 'Chapter 1: Trends', completed: false },
        { name: 'Chapter 2: Trading Ranges', completed: false },
        { name: 'Chapter 3: Support and Resistance', completed: false },
        { name: 'Chapter 4: Chart Patterns', completed: false },
        { name: 'Chapter 5: Oscillators', completed: false },
        { name: 'Chapter 6: Reaction Count', completed: false },
        { name: 'Chapter 7: Run Days', completed: false },
        { name: 'Chapter 8: Technical Indicators', completed: false },
        { name: 'Chapter 9: Moving Averages', completed: false },
        { name: 'Chapter 10: Is Chart Analysis Still Valid?', completed: false },
        { name: 'Chapter 11: Midtrend Entry and Pyramiding', completed: false },
        { name: 'Chapter 12: Choosing Stop-Loss Points', completed: false },
        { name: 'Chapter 13: The Planned Trading Approach', completed: false },
        { name: 'Chapter 14: Eighty-Two Trading Rules', completed: false },
        { name: 'Chapter 15: Market Wisdom', completed: false },
      ],
    },
    {
      name: 'Technical Analysis of the Financial Markets — John J. Murphy',
      modules: [
        { name: 'Chapter 1: Introduction to Technical Analysis', completed: false },
        { name: 'Chapter 2: The Philosophy of Technical Analysis', completed: false },
        { name: 'Chapter 3: The Basics of Chart Construction', completed: false },
        { name: 'Chapter 4: Trends', completed: false },
        { name: 'Chapter 5: Support and Resistance', completed: false },
        { name: 'Chapter 6: Major Reversal Patterns', completed: false },
        { name: 'Chapter 7: Continuation Patterns', completed: false },
        { name: 'Chapter 8: Volume and Open Interest', completed: false },
        { name: 'Chapter 9: Moving Averages', completed: false },
        { name: 'Chapter 10: Oscillators', completed: false },
        { name: 'Chapter 11: Indicators', completed: false },
        { name: 'Chapter 12: Technical Analysis in Practice', completed: false },
        { name: 'Chapter 13: Putting it All Together', completed: false },
      ],
    },
    {
      name: 'Currency Trading for Dummies — Brian Dolan',
      modules: [
        { name: 'Chapter 1: Currency Trading 101', completed: false },
        { name: 'Chapter 2: What is the Forex Market?', completed: false },
        { name: 'Chapter 3: Who Trades Currencies? Meet the Players', completed: false },
        { name: 'Chapter 4: Major Currency Pairs', completed: false },
        { name: 'Chapter 5: Minor Currency Pairs', completed: false },
        { name: 'Chapter 6: Cross-Currency Trading', completed: false },
        { name: 'Chapter 7: Getting Started', completed: false },
        { name: 'Chapter 8: Fundamental Analysis', completed: false },
        { name: 'Chapter 9: Technical Analysis', completed: false },
        { name: 'Chapter 10: Creating Your Trading Plan', completed: false },
        { name: 'Chapter 11: Risk Management', completed: false },
        { name: 'Chapter 12: Advanced Trading Techniques', completed: false },
        { name: 'Chapter 13: Becoming a Successful Trader', completed: false },
      ],
    },
    {
      name: 'One Up On Wall Street — Peter Lynch',
      modules: [
        { name: 'Chapter 1: The Making of a Stockpicker', completed: false },
        { name: 'Chapter 2: The Wall Street Oxymorons', completed: false },
        { name: 'Chapter 3: Is This Gambling, or What?', completed: false },
        { name: 'Chapter 4: Passing the Mirror Test', completed: false },
        { name: 'Chapter 5: Is This a Good Market?', completed: false },
        { name: 'Chapter 6: Stalking the Tenbagger', completed: false },
        { name: "Chapter 7: I've Got It, I've Got It—What Is It?", completed: false },
        { name: 'Chapter 8: The Perfect Stock, What a Deal!', completed: false },
        { name: "Chapter 9: Stocks I'd Avoid", completed: false },
        { name: 'Chapter 10: Earnings, Earnings, Earnings', completed: false },
        { name: 'Chapter 11: The Two-Minute Drill', completed: false },
        { name: 'Chapter 12: Getting the Facts', completed: false },
        { name: 'Chapter 13: Some Famous Numbers', completed: false },
        { name: 'Chapter 14: Rechecking the Story', completed: false },
        { name: 'Chapter 15: The Final Checklist', completed: false },
      ],
    },
    {
      name: "How to Make Money in Stocks — William J. O'Neil",
      modules: [
        { name: 'Chapter 1: The Most Important Thing', completed: false },
        { name: 'Chapter 2: The Three Types of Companies', completed: false },
        { name: 'Chapter 3: Seven Common Characteristics of Winning Stocks', completed: false },
        { name: 'Chapter 4: Common Investor Mistakes', completed: false },
        { name: 'Chapter 5: The CAN SLIM Investing System', completed: false },
        { name: 'Chapter 6: How to Identify a Properly Formed Base', completed: false },
        { name: 'Chapter 7: Buy Rules for Winning Stocks', completed: false },
        { name: 'Chapter 8: How to Sell', completed: false },
        { name: 'Chapter 9: Market Trends', completed: false },
        { name: 'Chapter 10: Price and Volume Action', completed: false },
        { name: 'Chapter 11: Developing Your Investment Plan', completed: false },
      ],
    },
    {
      name: 'Day Trading and Swing Trading the Currency Market — Kathy Lien',
      modules: [
        { name: 'Chapter 1: Understanding Forex Markets', completed: false },
        { name: 'Chapter 2: Market Participants', completed: false },
        { name: 'Chapter 3: Currency Pairs', completed: false },
        { name: 'Chapter 4: What Moves the Currency Market?', completed: false },
        { name: 'Chapter 5: Trading Strategies for Major Market Conditions', completed: false },
        { name: 'Chapter 6: Technical Trading Strategies', completed: false },
        { name: 'Chapter 7: Fundamental Trading Strategies', completed: false },
        { name: 'Chapter 8: Profitable Patterns and Setups', completed: false },
        { name: 'Chapter 9: Risk Management in FX', completed: false },
        { name: 'Chapter 10: Day Trading Tactics', completed: false },
        { name: 'Chapter 11: Swing Trading Tactics', completed: false },
        { name: 'Chapter 12: Advanced Strategies', completed: false },
      ],
    },
    {
      name: 'Market Wizards — Jack Schwager',
      modules: [
        { name: 'Preface', completed: false },
        { name: 'Prologue', completed: false },
        { name: 'Marty Schwartz: Champion Trader', completed: false },
        { name: 'James B. Rogers, Jr.: Buying Value and Selling Hysteria', completed: false },
        { name: 'Mark Weinstein: High-Percentage Trader', completed: false },
        { name: 'Brian Gelber: Trader and Volume', completed: false },
        { name: 'Tom Baldwin: Trading T-Bonds', completed: false },
        { name: 'Tony Saliba: Options Trader', completed: false },
        { name: 'Dr. Van K. Tharp: Trading Psychology', completed: false },
        { name: 'Ed Seykota: Systems Trading', completed: false },
        { name: 'Interview Summaries', completed: false },
      ],
    },
    {
      name: 'How to Day Trade for a Living — Andrew Aziz',
      modules: [
        { name: 'Chapter 1: Why Day Trade?', completed: false },
        { name: 'Chapter 2: Market Basics', completed: false },
        { name: 'Chapter 3: Day Trading Tools', completed: false },
        { name: 'Chapter 4: Building a Strategy', completed: false },
        { name: 'Chapter 5: Developing a Trading Plan', completed: false },
        { name: 'Chapter 6: Day Trading Strategies', completed: false },
        { name: 'Chapter 7: Money Management', completed: false },
        { name: 'Chapter 8: Psychology and Risk', completed: false },
        { name: 'Chapter 9: Getting Started', completed: false },
        { name: 'Chapter 10: Advanced Tips', completed: false },
      ],
    },
    {
      name: 'Volume Price Analysis — Anna Coulling',
      modules: [
        { name: "Chapter 1: There's Nothing New in Trading", completed: false },
        { name: 'Chapter 2: Why Volume', completed: false },
        { name: 'Chapter 3: The Right Price', completed: false },
        { name: 'Chapter 4: Volume Price Analysis - First Principles', completed: false },
        { name: 'Chapter 5: Building the Picture', completed: false },
        { name: 'Chapter 6: The Next Level', completed: false },
        { name: 'Chapter 7: Support and Resistance Explained', completed: false },
        { name: 'Chapter 8: Dynamic Trends and Trend Lines', completed: false },
        { name: 'Chapter 9: Volume at Price (VAP)', completed: false },
        { name: 'Chapter 10: Examples', completed: false },
        { name: 'Chapter 11: Putting it All Together', completed: false },
        { name: 'Chapter 12: Volume and Price—The Next Generation', completed: false },
      ],
    },
    {
      name: 'A Complete Guide to Volume Price Analysis — Anna Coulling',
      modules: [
        { name: "Chapter 1: There's Nothing New in Trading", completed: false },
        { name: 'Chapter 2: Why Volume', completed: false },
        { name: 'Chapter 3: The Right Price', completed: false },
        { name: 'Chapter 4: Volume Price Analysis - First Principles', completed: false },
        { name: 'Chapter 5: Building the Picture', completed: false },
        { name: 'Chapter 6: The Next Level', completed: false },
        { name: 'Chapter 7: Support and Resistance Explained', completed: false },
        { name: 'Chapter 8: Dynamic Trends and Trend Lines', completed: false },
        { name: 'Chapter 9: Volume at Price (VAP)', completed: false },
        { name: 'Chapter 10: Volume Price Analysis Examples', completed: false },
        { name: 'Chapter 11: Putting it All Together', completed: false },
        { name: 'Chapter 12: Volume and Price—The Next Generation', completed: false },
      ],
    },
    {
      name: 'The New Market Wizards — Jack Schwager',
      modules: [
        { name: 'Preface', completed: false },
        { name: 'Prologue', completed: false },
        { name: 'Misadventures in Trading', completed: false },
        { name: 'Bill Lipschutz: The Sultan of Currencies', completed: false },
        { name: 'Randy McKay: Veteran Trader', completed: false },
        { name: 'Linda Bradford Raschke: Reading the Music of the Markets', completed: false },
        { name: 'CRT: The Trading Machine', completed: false },
        { name: 'Mark Ritchie: God in the Pits', completed: false },
        { name: 'Joe Ritchie: The Intuitive Theoretician', completed: false },
        { name: 'Blair Hull: Getting the Edge', completed: false },
        { name: 'Jeff Yass: The Mathematics of Strategy', completed: false },
        { name: 'The Psychology of Trading', completed: false },
        { name: 'Zen and the Art of Trading', completed: false },
        { name: 'Charles Faulkner: The Mind of an Achiever', completed: false },
        { name: 'Institutional Trader Interviews', completed: false },
      ],
    },
    {
      name: 'Trade Like a Stock Market Wizard — Mark Minervini',
      modules: [
        { name: 'Chapter 1: An Introduction Worth Reading', completed: false },
        { name: 'Chapter 2: What You Need to Know First', completed: false },
        { name: 'Chapter 3: Specific Entry Point Analysis: The SEPA Strategy', completed: false },
        { name: 'Chapter 4: Value Comes at a Price', completed: false },
        { name: 'Chapter 5: Trading with the Trend', completed: false },
        { name: 'Chapter 6: Categories, Industry Groups, and Catalysts', completed: false },
        { name: 'Chapter 7: Fundamentals to Focus On', completed: false },
        { name: 'Chapter 8: Assessing Earnings Quality', completed: false },
        { name: 'Chapter 9: Follow the Leaders', completed: false },
        { name: 'Chapter 10: A Picture Is Worth a Million Dollars', completed: false },
        { name: "Chapter 11: Don't Just Buy What You Know", completed: false },
        { name: 'Chapter 12: The Nature of Risk', completed: false },
        { name: 'Chapter 13: How to Deal with and Control Risk', completed: false },
      ],
    },
    {
      name: 'Beat the Forex Dealer — Agustin Silvani',
      modules: [
        { name: 'Acknowledgments', completed: false },
        { name: 'Introduction', completed: false },
        { name: 'Part I: Through the Eyes of a Trader - On Markets', completed: false },
        { name: 'Part I: Through the Eyes of a Trader - The Currency Market', completed: false },
        { name: 'Part I: Through the Eyes of a Trader - A Rare Breed', completed: false },
        { name: 'Part I: Through the Eyes of a Trader - FX Dealers', completed: false },
        { name: "Part I: Through the Eyes of a Trader - Today's FX Market", completed: false },
        { name: 'Part I: Through the Eyes of a Trader - The Players', completed: false },
        { name: 'Part II: The Retail Side of Things - Card Stacking', completed: false },
        { name: "Part II: The Retail Side of Things - Don't Trust Your FCM", completed: false },
        { name: 'Part II: The Retail Side of Things - Third-Party Services', completed: false },
        { name: 'Part II: The Retail Side of Things - Fighting Back', completed: false },
        { name: 'Part III: Joining the 10% - Becoming a Great Trader', completed: false },
        { name: 'Part III: Joining the 10% - Picking the Right Approach', completed: false },
        { name: 'Part IV: FX Trading Tips - Dealer Trades', completed: false },
        { name: 'Part IV: FX Trading Tips - Trading Against Dealers', completed: false },
        { name: 'Part IV: FX Trading Tips - The Big Figure Trade', completed: false },
        { name: 'Part IV: FX Trading Tips - The Friday to Sunday Extension', completed: false },
        { name: 'Part IV: FX Trading Tips - Sticking it to Your Dealer', completed: false },
        { name: 'Part V: The Future - The End of the Beginning', completed: false },
        { name: "Appendix: Trading How-To's, FX Glossary, Maxims", completed: false },
      ],
    },
    {
      name: 'Mastering the Trade — John Carter',
      modules: [
        { name: 'Chapter 1: What Really Causes the Markets to Move?', completed: false },
        { name: "Chapter 2: Psychology 101: What Didn't They Teach in School?", completed: false },
        { name: 'Chapter 3: Hardware and Software—Top Tools for Traders', completed: false },
        { name: 'Chapter 4: Futures Markets 101—Understanding the Basics', completed: false },
        { name: 'Chapter 5: Stock Options: How Do They Work?', completed: false },
        { name: 'Chapter 6: The Stock Market Is Now Open', completed: false },
        { name: 'Chapter 7: The Opening Gap', completed: false },
        { name: 'Chapter 8: Pivot Points', completed: false },
        { name: 'Chapter 9: Tick Fades', completed: false },
        { name: 'Chapter 10: Reverting Back to the Mean', completed: false },
        { name: 'Chapter 11: The Squeeze', completed: false },
        { name: 'Chapter 12: Brick Plays', completed: false },
        { name: 'Chapter 13: The 3:52 Play', completed: false },
        { name: 'Chapter 14: HOLP and LOHP', completed: false },
        { name: 'Chapter 15: Propulsion Plays', completed: false },
        { name: 'Chapter 16: Gold Trades', completed: false },
        { name: 'Chapter 17: Live Trading Room', completed: false },
        { name: 'Chapter 18: Premarket Checklist', completed: false },
        { name: "Chapter 19: Trader's Business Plan", completed: false },
        { name: 'Chapter 20: Tips and Tricks', completed: false },
        { name: 'Chapter 21: Mastering the Trade', completed: false },
      ],
    },
    {
      name: 'Systematic Trading — Robert Carver',
      modules: [
        { name: 'Preface', completed: false },
        { name: 'Introduction', completed: false },
        { name: 'Part 1: Theory - The Theory Behind Systematic Trading', completed: false },
        { name: 'Part 1: Theory - Human Biases', completed: false },
        { name: 'Part 1: Theory - The Death of Rational Economic Man', completed: false },
        { name: 'Part 2: Toolbox - Designing Effective Strategies', completed: false },
        { name: 'Part 2: Toolbox - Position Management Framework', completed: false },
        { name: 'Part 2: Toolbox - Portfolio Allocation', completed: false },
        { name: 'Part 2: Toolbox - Backtesting', completed: false },
        { name: 'Part 3: Framework - Creating Rules', completed: false },
        { name: 'Part 3: Framework - Fully Systematic/Discretionary Management', completed: false },
        { name: 'Part 4: Practice - Application Examples', completed: false },
        { name: 'Epilogue: What Makes a Good Systematic Trader?', completed: false },
        { name: 'Appendices: Resources, Trading Rules, Portfolio Optimization, Details', completed: false },
      ],
    },
    {
      name: 'Algorithmic Trading — Ernest P. Chan',
      modules: [
        { name: 'Preface', completed: false },
        { name: 'Chapter 1: Backtesting and Automated Execution', completed: false },
        { name: 'Chapter 2: Basics of Mean Reversion', completed: false },
        { name: 'Chapter 3: Implementing Mean Reversion Strategies', completed: false },
        { name: 'Chapter 4: Mean Reversion of Stocks and ETFs', completed: false },
        { name: 'Chapter 5: Mean Reversion of Currencies and Futures', completed: false },
        { name: 'Chapter 6: Interday Momentum Strategies', completed: false },
        { name: 'Chapter 7: Intraday Momentum Strategies', completed: false },
        { name: 'Chapter 8: Risk Management', completed: false },
        { name: 'Conclusion', completed: false },
        { name: 'Bibliography', completed: false },
        { name: 'About the Author', completed: false },
      ],
    },
    {
      name: 'Reminiscences of a Stock Operator — Edwin Lefevre',
      modules: [
        { name: 'Chapter 1: The Early Years — Lessons from the Bucket Shops', completed: false },
        { name: 'Chapter 2: Wall Street and the Perils of Leverage', completed: false },
        { name: 'Chapter 3: The Importance of Market Timing and Patience', completed: false },
        { name: 'Chapter 4: Overcoming Adversity and Learning from Mistakes', completed: false },
        { name: 'Chapter 5: The Art of Short Selling and Market Manipulation', completed: false },
        { name: 'Chapter 6: Expanding Horizons — Trading Commodities and Beyond', completed: false },
        { name: 'Chapter 7: Lessons in Risk — Managing Drawdowns and Setbacks', completed: false },
        { name: 'Chapter 8: The Psychology of Speculation — Controlling Greed and Fear', completed: false },
        { name: "Chapter 9: Manipulating the Market — The Operator's Art", completed: false },
        { name: 'Chapter 10: Dealing with Market Insiders and Tips', completed: false },
        { name: 'Chapter 11: Surviving Booms and Busts — The Market Cycle', completed: false },
        { name: 'Chapter 12: Bankruptcy and Recovery — Rising from Ruin', completed: false },
        { name: 'Chapter 13: Government Interventions and Unforeseen Events', completed: false },
        { name: 'Chapter 14: On Market Regulations and Ethics', completed: false },
        { name: 'Chapter 15: Losing Streaks — Handling Extended Adversity', completed: false },
        { name: 'Chapter 16: Bankrupt Again — Lessons in Humility', completed: false },
        { name: 'Chapter 17: Rebuilding Reputation and Capital', completed: false },
        { name: 'Chapter 18: The Power of Observation — Tape Reading Mastery', completed: false },
        { name: 'Chapter 19: The Final Years — Wisdom and Trading Rules', completed: false },
        { name: 'Chapter 20: Legacy in the Markets — Reflections and Enduring Principles', completed: false },
      ],
    },
  ]

  // Create trading courses with modules
  if (existingTradingCourses.length === 0) {
    for (const courseData of tradingCoursesData) {
      const { modules, ...courseInfo } = courseData
      const course = await prisma.tradingCourse.create({
        data: {
          name: courseInfo.name,
          description: courseInfo.description,
          userId: user.id,
          startDate: transformationStartDate,
          targetDate: targetDate,
          modules: {
            create: modules.map((module, index) => ({
              name: module.name,
              order: index + 1,
              completed: module.completed,
              completedAt: module.completed ? new Date() : null,
            })),
          },
        },
        include: {
          modules: true,
        },
      })
      console.log(`✅ Created trading course: ${course.name} with ${course.modules.length} modules`)
    }
  }

  console.log('🎉 Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Error during seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
